/* =========================================================================
   PESCA RIOJA — Datos de demostración (MOCK)
   Todas las coordenadas, cupos, precios y valores de caudal/temperatura son
   ILUSTRATIVOS. No constituyen normativa oficial. Antes de pescar, consulta
   siempre la Orden Anual de Pesca del Gobierno de La Rioja.
   ========================================================================= */

// ---- Tipos de tramo (leyenda) -------------------------------------------
const TRAMO_TYPES = {
  libre:      { label: { es: 'Tramo libre',                 en: 'Free stretch',              eu: 'Tarte librea',             fr: 'Tronçon libre' },              color: '#22C55E' },
  coto:       { label: { es: 'Coto de pesca (cupo/permiso)', en: 'Fishing reserve (permit)',  eu: 'Arrantza-eremua (baimena)',fr: 'Réserve (permis requis)' },     color: '#0284C7' },
  sinMuerte:  { label: { es: 'Sin muerte (captura y suelta)',en: 'No-kill (catch & release)', eu: 'Heriotzarik gabe',          fr: 'Sans tuer (attrape et relâche)'},color: '#EAB308' },
  intensivo:  { label: { es: 'Intensivo / repoblado',        en: 'Intensive / restocked',     eu: 'Intentsiboa / birpopulatua',fr: 'Intensif / repeuplé' },        color: '#9333EA' },
  escolar:    { label: { es: 'Escolar / iniciación',         en: 'Beginner / school',          eu: 'Eskolako / hasierakoa',    fr: 'Débutant / initiation' },       color: '#94A3B8' },
  vedado:     { label: { es: 'Vedado / prohibido',           en: 'Closed / no fishing',        eu: 'Debekatua',                fr: 'Interdit' },                    color: '#DC2626' },
};

// ---- Especies -------------------------------------------------------------
const SPECIES = [
  {
    id: 'trucha-comun',
    nombre: { es: 'Trucha común', en: 'Brown trout', eu: 'Amuarrain arrunta', fr: 'Truite fario' },
    cientifico: 'Salmo trutta',
    origen: 'autoctona',
    color: '#B45309',
    icon: 'fish',
    tallaMedia: '22–30 cm',
    tallaMaxima: '58 cm (registro de la cuenca)',
    tallaMinimaLegal: '21 cm',
    cupo: '4 piezas/día (según tramo)',
    descripcion: 'Coloración parda-dorada con puntos negros y rojos rodeados de halo claro. Cuerpo fusiforme, robusto. Es la especie reina de los ríos de montaña riojanos.',
    habitat: 'Prefiere pozas profundas con corriente moderada, zonas de sombra bajo vegetación de ribera y cabeceras de aguas frías y bien oxigenadas.',
    freza: 'Noviembre–enero, en zonas de grava de cabecera.',
    conservacion: 'Autóctona. Poblaciones sensibles a la calidad del agua; muchos tramos altos son "sin muerte" para protegerla.',
    tecnicas: [
      'Mosca seca en pozas tranquilas al atardecer.',
      'Ninfa a la vista en corrientes rápidas y rabiones.',
      'Spinning ligero con cucharilla en aguas con más caudal.',
    ],
    senuelos: ['Mosca seca: Adams nº14–16, Elk Hair Caddis nº14', 'Ninfa: Perdigón nº16–18, Pheasant Tail nº14', 'Cucharilla ondulante 2–4 g'],
    anzuelos: ['Mosca: anzuelo curvado nº14–16', 'Cebo natural: nº8–10 de caña larga'],
    cebos: ['Lombriz de tierra (donde esté permitido)', 'Saltamontes en verano', 'Larvas de tricóptero'],
    mejorEpoca: 'Marzo–junio y septiembre–octubre',
    mejorHora: 'Amanecer y atardecer',
    condicionesIdeales: 'Cielo nublado, caudal medio-alto, agua entre 8–14 °C',
    manejo: 'Usa unhooking mat y pinzas sin púa; minimiza el tiempo fuera del agua (<10 s) en captura y suelta.',
  },
  {
    id: 'trucha-arcoiris',
    nombre: { es: 'Trucha arcoíris', en: 'Rainbow trout', eu: 'Amuarrain ostadar', fr: 'Truite arc-en-ciel' },
    cientifico: 'Oncorhynchus mykiris',
    origen: 'introducida',
    color: '#0891B2',
    icon: 'fish',
    tallaMedia: '25–35 cm',
    tallaMaxima: '52 cm (repoblación)',
    tallaMinimaLegal: 'Sin talla mínima en tramos intensivos',
    cupo: '6 piezas/día en tramos intensivos',
    descripcion: 'Franja rosada-violeta iridiscente a lo largo del costado. Cuerpo más plateado que la trucha común. Especie de repoblación, muy activa y combativa al anzuelo.',
    habitat: 'Tramos de repoblación intensiva y embalses; tolera aguas algo más cálidas que la trucha común.',
    freza: 'No suele reproducirse establemente en la cuenca; se mantiene por repoblación.',
    conservacion: 'Especie introducida, gestionada en tramos "intensivo/repoblado" específicos para pesca deportiva de alto rendimiento.',
    tecnicas: ['Spinning con cucharilla brillante', 'Cebo natural en fondo', 'Mosca ninfa de colores vivos'],
    senuelos: ['Cucharilla giratoria plateada/naranja 3–5 g', 'Ninfa Rojo Ardilla nº12', 'Vinilo micro 5 cm color chartreuse'],
    anzuelos: ['Triple anzuelo nº10 en cucharilla', 'Anzuelo simple nº10–12 con cebo'],
    cebos: ['Maíz dulce (donde esté permitido)', 'Pasta preparada para trucha', 'Lombriz'],
    mejorEpoca: 'Todo el año en tramos intensivos (repoblación periódica)',
    mejorHora: 'Media mañana, tras la suelta de piezas',
    condicionesIdeales: 'Cualquier condición; algo más activa con sol suave',
    manejo: 'Si el tramo es intensivo normalmente se permite muerte dentro de cupo; respeta siempre la talla y el cupo señalizado.',
  },
  {
    id: 'barbo-iberico',
    nombre: { es: 'Barbo ibérico', en: 'Iberian barbel', eu: 'Barbo iberiarra', fr: 'Barbeau ibérique' },
    cientifico: 'Luciobarbus graellsii',
    origen: 'autoctona',
    color: '#65A30D',
    icon: 'fish',
    tallaMedia: '30–45 cm',
    tallaMaxima: '70 cm',
    tallaMinimaLegal: '25 cm',
    cupo: 'Sin límite en tramos libres (captura y suelta recomendada)',
    descripcion: 'Cuerpo alargado y cilíndrico, boca inferior con barbillas características. Habitual en los tramos medios y bajos de los ríos riojanos, incluido el Ebro.',
    habitat: 'Corrientes moderadas sobre fondo de grava y arena, tramos medios-bajos de ríos y el propio Ebro.',
    freza: 'Mayo–julio, remonta pequeños afluentes para desovar.',
    conservacion: 'Autóctono, poblaciones estables. Buen indicador de calidad del agua.',
    tecnicas: ['Pesca a fondo con plomada', 'Feeder con cebador', 'Float fishing en corriente suave'],
    senuelos: ['Cebador con masa de pan/atún', 'Boilies pequeños 12–14 mm'],
    anzuelos: ['Anzuelo nº6–8 de acero fuerte', 'Anzuelo circular para captura y suelta'],
    cebos: ['Lombriz', 'Maíz', 'Masa artesanal de pan y queso'],
    mejorEpoca: 'Mayo–septiembre',
    mejorHora: 'Mediodía y tarde en aguas cálidas',
    condicionesIdeales: 'Agua templada 15–20 °C, caudal estable',
    manejo: 'Especie robusta pero de piel sensible; usa red sin nudos y devuelve rápido en captura y suelta.',
  },
  {
    id: 'black-bass',
    nombre: { es: 'Black-bass', en: 'Largemouth bass', eu: 'Black bass', fr: 'Black-bass' },
    cientifico: 'Micropterus salmoides',
    origen: 'introducida',
    color: '#166534',
    icon: 'fish',
    tallaMedia: '25–40 cm',
    tallaMaxima: '55 cm',
    tallaMinimaLegal: '30 cm (especie exótica: gestión especial)',
    cupo: 'Sin obligación de devolución — se recomienda no reintroducir',
    descripcion: 'Cuerpo robusto verde oliva con banda lateral oscura irregular. Depredador voraz asociado a embalses y remansos profundos.',
    habitat: 'Embalses (Mansilla, González Lacasa) y remansos profundos de ríos de tramo bajo.',
    freza: 'Abril–junio, el macho construye y guarda el nido.',
    conservacion: 'Especie exótica invasora: su suelta en otras aguas está prohibida por ley.',
    tecnicas: ['Casting con señuelos de superficie al amanecer', 'Carolina rig con vinilo junto a estructuras', 'Spinnerbait en aguas turbias'],
    senuelos: ['Popper de superficie 8 cm', 'Vinilo craw 10 cm color verde/marrón', 'Spinnerbait doble pala'],
    anzuelos: ['Anzuelo offset nº2/0–4/0 para vinilo', 'Anzuelo triple en señuelos duros'],
    cebos: ['Pesca exclusivamente con señuelo artificial (cebo natural restringido en muchos embalses)'],
    mejorEpoca: 'Mayo–octubre',
    mejorHora: 'Amanecer y anochecer, también noches de verano',
    condicionesIdeales: 'Agua cálida >18 °C, poco viento, luz baja',
    manejo: 'No trasladar ejemplares vivos a otro embalse o río bajo ningún concepto (especie invasora).',
  },
  {
    id: 'lucioperca',
    nombre: { es: 'Lucioperca', en: 'Zander', eu: 'Luzioperka', fr: 'Sandre' },
    cientifico: 'Sander lucioperca',
    origen: 'introducida',
    color: '#475569',
    icon: 'fish',
    tallaMedia: '40–60 cm',
    tallaMaxima: '85 cm',
    tallaMinimaLegal: '40 cm',
    cupo: '2 piezas/día en embalses autorizados',
    descripcion: 'Cuerpo alargado grisáceo con bandas verticales tenues, ojos grandes adaptados a la caza en aguas turbias o con poca luz.',
    habitat: 'Embalses profundos y tramos bajos de gran caudal; caza en bancos y cambios de profundidad.',
    freza: 'Abril–mayo sobre fondos duros.',
    conservacion: 'Especie introducida, gestionada en aguas concretas por su interés deportivo.',
    tecnicas: ['Vertical jigging sobre bancos de peces pasto', 'Curricán lento en embalse', 'Drop-shot junto a estructuras'],
    senuelos: ['Vinilo shad 10–12 cm', 'Cabeza plomada 10–20 g según profundidad'],
    anzuelos: ['Anzuelo jig nº2/0–3/0'],
    cebos: ['Pesca principalmente con señuelo; cebo vivo restringido'],
    mejorEpoca: 'Todo el año, mejor en otoño-invierno',
    mejorHora: 'Anochecer y noche',
    condicionesIdeales: 'Aguas con turbidez media, poca luz',
    manejo: 'Sujeta siempre por debajo de la mandíbula, evita dañar las branquias al desanzuelar.',
  },
];

function speciesById(id) {
  return SPECIES.find((s) => s.id === id);
}

// ---- Ríos y tramos (GeoJSON-like, coordenadas orientativas) --------------
// Cada tramo: { id, tipo, nombre, rio, municipio, km, modalidad[], cupo, tallaMinima,
//   vedaInicio, vedaFin, precio, permisoUrl, especies[], caudalM3s, tempAguaC,
//   transparencia, accesoDificultad, vadeable, coords: [[lat,lng], ...] }

const RIVERS = [
  {
    id: 'ebro',
    nombre: 'Ebro',
    color: '#0369A1',
    tramos: [
      {
        id: 'ebro-haro',
        nombre: 'Ebro — Haro a San Vicente',
        municipio: 'Haro',
        km: 6.4,
        tipo: 'libre',
        modalidad: ['mosca', 'spinning', 'cebo natural'],
        cupo: '4 piezas/día',
        tallaMinima: '21 cm (trucha), 25 cm (barbo)',
        veda: '1 marzo – 3er domingo de agosto',
        precio: 'Gratuito',
        permisoUrl: 'https://www.larioja.org/pesca',
        especies: ['barbo-iberico', 'trucha-arcoiris'],
        caudalM3s: 42.5, tempAguaC: 14.2, transparencia: 'Media',
        accesoDificultad: 'Fácil', vadeable: false,
        coords: [[42.5763, -2.8437], [42.5602, -2.8010], [42.5480, -2.7590]],
      },
      {
        id: 'ebro-logrono',
        nombre: 'Ebro — Tramo urbano Logroño',
        municipio: 'Logroño',
        km: 4.1,
        tipo: 'sinMuerte',
        modalidad: ['mosca', 'spinning sin muerte'],
        cupo: '0 (captura y suelta obligatoria)',
        tallaMinima: 'No aplica (devolución obligatoria)',
        veda: 'Abierto todo el año, captura y suelta',
        precio: 'Gratuito',
        permisoUrl: 'https://www.larioja.org/pesca',
        especies: ['barbo-iberico', 'black-bass'],
        caudalM3s: 58.1, tempAguaC: 15.6, transparencia: 'Baja',
        accesoDificultad: 'Muy fácil (paseo fluvial)', vadeable: false,
        coords: [[42.4780, -2.4720], [42.4660, -2.4480], [42.4540, -2.4220]],
      },
      {
        id: 'ebro-alfaro',
        nombre: 'Ebro — Coto de Alfaro',
        municipio: 'Alfaro',
        km: 5.2,
        tipo: 'coto',
        modalidad: ['cebo natural', 'spinning'],
        cupo: '3 piezas/día',
        tallaMinima: '25 cm (barbo)',
        veda: '1 marzo – 3er domingo de agosto',
        precio: '18 €/día — permiso en sede electrónica',
        permisoUrl: 'https://www.larioja.org/pesca',
        especies: ['barbo-iberico', 'lucioperca'],
        caudalM3s: 63.0, tempAguaC: 16.4, transparencia: 'Media',
        accesoDificultad: 'Fácil', vadeable: false,
        coords: [[42.3180, -2.0150], [42.3080, -1.9820], [42.2990, -1.9520]],
      },
    ],
  },
  {
    id: 'oja',
    nombre: 'Oja',
    color: '#166534',
    tramos: [
      {
        id: 'oja-ezcaray',
        nombre: 'Oja — Cabecera Ezcaray',
        municipio: 'Ezcaray',
        km: 3.0,
        tipo: 'vedado',
        modalidad: ['ninguna — cierre total'],
        cupo: '0',
        tallaMinima: 'No aplica',
        veda: 'Cerrado todo el año — zona de protección de freza',
        precio: 'No disponible',
        permisoUrl: 'https://www.larioja.org/pesca',
        especies: ['trucha-comun'],
        caudalM3s: 2.1, tempAguaC: 9.8, transparencia: 'Alta',
        accesoDificultad: 'Difícil (sendero de montaña)', vadeable: true,
        coords: [[42.3253, -3.0000], [42.3660, -2.9820], [42.3980, -2.9650]],
      },
      {
        id: 'oja-santo-domingo',
        nombre: 'Oja — Santo Domingo de la Calzada',
        municipio: 'Santo Domingo de la Calzada',
        km: 4.6,
        tipo: 'intensivo',
        modalidad: ['mosca', 'spinning', 'cebo natural'],
        cupo: '6 piezas/día (repoblación semanal)',
        tallaMinima: 'Sin talla mínima',
        veda: '1 marzo – 3er domingo de agosto',
        precio: '12 €/día — permiso en sede electrónica',
        permisoUrl: 'https://www.larioja.org/pesca',
        especies: ['trucha-arcoiris', 'trucha-comun'],
        caudalM3s: 4.4, tempAguaC: 11.5, transparencia: 'Alta',
        accesoDificultad: 'Fácil', vadeable: true,
        coords: [[42.4405, -2.9538], [42.4520, -2.9260], [42.4610, -2.9010]],
      },
    ],
  },
  {
    id: 'tiron',
    nombre: 'Tirón',
    color: '#15803D',
    tramos: [
      {
        id: 'tiron-medio',
        nombre: 'Tirón — Tramo medio Cuzcurrita',
        municipio: 'Cuzcurrita de Río Tirón',
        km: 5.8,
        tipo: 'libre',
        modalidad: ['mosca', 'spinning', 'cebo natural'],
        cupo: '4 piezas/día',
        tallaMinima: '21 cm',
        veda: '1 marzo – 3er domingo de agosto',
        precio: 'Gratuito',
        permisoUrl: 'https://www.larioja.org/pesca',
        especies: ['trucha-comun'],
        caudalM3s: 3.2, tempAguaC: 10.9, transparencia: 'Alta',
        accesoDificultad: 'Media', vadeable: true,
        coords: [[42.5150, -2.9280], [42.5320, -2.9010], [42.5480, -2.8720]],
      },
    ],
  },
  {
    id: 'najerilla',
    nombre: 'Najerilla',
    color: '#0EA5E9',
    tramos: [
      {
        id: 'najerilla-cabecera',
        nombre: 'Najerilla — Cabecera / Embalse Mansilla',
        municipio: 'Anguiano',
        km: 3.5,
        tipo: 'escolar',
        modalidad: ['cebo natural (iniciación)'],
        cupo: '2 piezas/día',
        tallaMinima: '19 cm',
        veda: '1 marzo – 3er domingo de agosto',
        precio: 'Gratuito (zona de iniciación)',
        permisoUrl: 'https://www.larioja.org/pesca',
        especies: ['trucha-comun'],
        caudalM3s: 2.8, tempAguaC: 10.1, transparencia: 'Alta',
        accesoDificultad: 'Fácil', vadeable: true,
        coords: [[42.2757, -2.7728], [42.2950, -2.7600], [42.3150, -2.7480]],
      },
      {
        id: 'najerilla-najera',
        nombre: 'Najerilla — Coto de Nájera',
        municipio: 'Nájera',
        km: 4.9,
        tipo: 'coto',
        modalidad: ['mosca', 'spinning'],
        cupo: '4 piezas/día',
        tallaMinima: '21 cm',
        veda: '1 marzo – 3er domingo de agosto',
        precio: '15 €/día — permiso en sede electrónica',
        permisoUrl: 'https://www.larioja.org/pesca',
        especies: ['trucha-comun', 'trucha-arcoiris'],
        caudalM3s: 5.6, tempAguaC: 12.3, transparencia: 'Media',
        accesoDificultad: 'Fácil', vadeable: true,
        coords: [[42.4159, -2.7325], [42.4230, -2.7180], [42.4310, -2.7010]],
      },
    ],
  },
  {
    id: 'iregua',
    nombre: 'Iregua',
    color: '#7C3AED',
    tramos: [
      {
        id: 'iregua-alto',
        nombre: 'Iregua — Alto (Villanueva de Cameros)',
        municipio: 'Villanueva de Cameros',
        km: 6.1,
        tipo: 'libre',
        modalidad: ['mosca', 'cebo natural'],
        cupo: '4 piezas/día',
        tallaMinima: '21 cm',
        veda: '1 marzo – 3er domingo de agosto',
        precio: 'Gratuito',
        permisoUrl: 'https://www.larioja.org/pesca',
        especies: ['trucha-comun'],
        caudalM3s: 1.9, tempAguaC: 9.4, transparencia: 'Alta',
        accesoDificultad: 'Media', vadeable: true,
        coords: [[42.1652, -2.6395], [42.1980, -2.6120], [42.2350, -2.5850]],
      },
      {
        id: 'iregua-bajo',
        nombre: 'Iregua — Bajo urbano',
        municipio: 'Islallana / Logroño',
        km: 3.4,
        tipo: 'sinMuerte',
        modalidad: ['mosca sin muerte'],
        cupo: '0 (devolución obligatoria)',
        tallaMinima: 'No aplica',
        veda: 'Abierto todo el año',
        precio: 'Gratuito',
        permisoUrl: 'https://www.larioja.org/pesca',
        especies: ['trucha-comun', 'barbo-iberico'],
        caudalM3s: 3.1, tempAguaC: 12.8, transparencia: 'Media',
        accesoDificultad: 'Fácil', vadeable: true,
        coords: [[42.4020, -2.5250], [42.4180, -2.5010], [42.4380, -2.4750]],
      },
    ],
  },
  {
    id: 'leza',
    nombre: 'Leza',
    color: '#DB2777',
    tramos: [
      {
        id: 'leza-coto',
        nombre: 'Leza — Coto Leza de Río Leza',
        municipio: 'Leza de Río Leza',
        km: 4.0,
        tipo: 'coto',
        modalidad: ['mosca', 'spinning'],
        cupo: '4 piezas/día',
        tallaMinima: '21 cm',
        veda: '1 marzo – 3er domingo de agosto',
        precio: '14 €/día — permiso en sede electrónica',
        permisoUrl: 'https://www.larioja.org/pesca',
        especies: ['trucha-comun'],
        caudalM3s: 1.6, tempAguaC: 10.7, transparencia: 'Alta',
        accesoDificultad: 'Media', vadeable: true,
        coords: [[42.3050, -2.4550], [42.3230, -2.4380], [42.3420, -2.4190]],
      },
    ],
  },
  {
    id: 'cidacos',
    nombre: 'Cidacos',
    color: '#EA580C',
    tramos: [
      {
        id: 'cidacos-arnedillo',
        nombre: 'Cidacos — Arnedillo',
        municipio: 'Arnedillo',
        km: 5.3,
        tipo: 'libre',
        modalidad: ['mosca', 'cebo natural'],
        cupo: '4 piezas/día',
        tallaMinima: '21 cm',
        veda: '1 marzo – 3er domingo de agosto',
        precio: 'Gratuito',
        permisoUrl: 'https://www.larioja.org/pesca',
        especies: ['trucha-comun', 'barbo-iberico'],
        caudalM3s: 2.4, tempAguaC: 13.1, transparencia: 'Media',
        accesoDificultad: 'Media', vadeable: true,
        coords: [[42.2266, -2.1000], [42.2410, -2.0780], [42.2560, -2.0540]],
      },
    ],
  },
  {
    id: 'alhama',
    nombre: 'Alhama',
    color: '#78350F',
    tramos: [
      {
        id: 'alhama-alto',
        nombre: 'Alhama — Cabecera Cervera',
        municipio: 'Cervera del Río Alhama',
        km: 2.8,
        tipo: 'vedado',
        modalidad: ['ninguna — cierre total'],
        cupo: '0',
        tallaMinima: 'No aplica',
        veda: 'Cerrado todo el año — recuperación de población',
        precio: 'No disponible',
        permisoUrl: 'https://www.larioja.org/pesca',
        especies: ['trucha-comun'],
        caudalM3s: 0.9, tempAguaC: 11.8, transparencia: 'Alta',
        accesoDificultad: 'Difícil', vadeable: true,
        coords: [[42.0270, -1.9680], [42.0430, -1.9520], [42.0610, -1.9340]],
      },
    ],
  },
];

function allTramos() {
  return RIVERS.flatMap((r) => r.tramos.map((t) => ({ ...t, rioId: r.id, rioNombre: r.nombre, rioColor: r.color })));
}

function tramoById(id) {
  return allTramos().find((t) => t.id === id);
}

// ---- Puntos de interés -----------------------------------------------------
const POIS = [
  { id: 'poi-1', tipo: 'parking', nombre: 'Aparcamiento Ebro — Haro', coords: [42.5745, -2.8395] },
  { id: 'poi-2', tipo: 'acceso', nombre: 'Acceso peatonal — San Vicente', coords: [42.5500, -2.7650] },
  { id: 'poi-3', tipo: 'guarda', nombre: 'Caseta de guarda — Alfaro', coords: [42.3080, -1.9800] },
  { id: 'poi-4', tipo: 'parking', nombre: 'Aparcamiento Coto Nájera', coords: [42.4225, -2.7190] },
  { id: 'poi-5', tipo: 'acampada', nombre: 'Zona de acampada — Ezcaray', coords: [42.3350, -2.9900] },
  { id: 'poi-6', tipo: 'refugio', nombre: 'Refugio de montaña — Villanueva de Cameros', coords: [42.1700, -2.6350] },
  { id: 'poi-7', tipo: 'parking', nombre: 'Aparcamiento Iregua urbano', coords: [42.4370, -2.4760] },
  { id: 'poi-8', tipo: 'acceso', nombre: 'Acceso peatonal — Leza', coords: [42.3240, -2.4370] },
];

// ---- Calendario de vedas (resumen por especie) ----------------------------
const VEDAS = [
  { especie: 'trucha-comun', apertura: '1 marzo', cierre: '3er domingo de agosto', notas: 'Cierre anticipado en tramos de cabecera por bajo caudal.' },
  { especie: 'trucha-arcoiris', apertura: 'Todo el año', cierre: 'Tramos intensivos', notas: 'Repoblación periódica, sin veda estacional.' },
  { especie: 'barbo-iberico', apertura: '1 marzo', cierre: '31 diciembre', notas: 'Veda de freza en afluentes pequeños, mayo–julio.' },
  { especie: 'black-bass', apertura: 'Todo el año', cierre: 'Embalses autorizados', notas: 'Prohibida su suelta en otras masas de agua.' },
  { especie: 'lucioperca', apertura: 'Todo el año', cierre: 'Embalses autorizados', notas: 'Mejor actividad en otoño-invierno.' },
];

// ---- Reseñas mock (persisten en localStorage bajo pesca-rioja-reviews) ---
const SEED_REVIEWS = {
  'ebro-haro': [
    { autor: 'Javi R.', estrellas: 5, texto: 'Buen tramo, fácil acceso y barbos grandes en verano.', fecha: '2026-06-12' },
  ],
  'najerilla-najera': [
    { autor: 'Marta L.', estrellas: 4, texto: 'El coto está muy bien cuidado, truchas de buen tamaño.', fecha: '2026-05-30' },
  ],
};

// ---- i18n -------------------------------------------------------------------
const I18N = {
  es: {
    appName: 'Pesca Rioja', tagline: 'La herramienta definitiva de pesca deportiva en La Rioja',
    searchPlaceholder: 'Buscar río, municipio o tramo…',
    filters: 'Filtros', species: 'Especie', tramoType: 'Tipo de tramo', difficulty: 'Dificultad', nearMe: 'Cerca de mí',
    legend: 'Leyenda', layers: 'Capas', satellite: 'Satélite', topo: 'Topográfico', standard: 'Estándar',
    tramoSheetLength: 'Longitud', tramoSheetModalidad: 'Modalidad permitida', tramoSheetCupo: 'Cupo', tramoSheetTalla: 'Talla mínima',
    tramoSheetVeda: 'Veda', tramoSheetPrecio: 'Permiso', tramoSheetSpecies: 'Especies presentes', tramoSheetConditions: 'Condiciones actuales',
    tramoSheetAccess: 'Acceso', tramoSheetGallery: 'Galería de la comunidad', tramoSheetReviews: 'Valoraciones', tramoSheetDirections: 'Cómo llegar',
    close: 'Cerrar', flow: 'Caudal', waterTemp: 'Temp. agua', clarity: 'Transparencia', difficultyLabel: 'Dificultad', wadeable: 'Vadeable',
    speciesBack: 'Volver al tramo', identification: 'Identificación', habitatBehavior: 'Hábitat y comportamiento', freza: 'Época de freza',
    conservation: 'Conservación', fishingGuide: 'Guía práctica de pesca', techniques: 'Técnicas recomendadas', lures: 'Señuelos recomendados',
    hooks: 'Anzuelos recomendados', naturalBaits: 'Cebos naturales', bestSeason: 'Mejor época', bestTime: 'Mejor franja horaria',
    idealConditions: 'Condiciones ideales', legalLimits: 'Límites legales', handling: 'Manejo captura y suelta',
    vedasTitle: 'Calendario de vedas', logbookTitle: 'Cuaderno de capturas', predictorTitle: 'Predicción de buen día de pesca',
    addCatch: 'Registrar captura', exportPdf: 'Exportar PDF', alertsTitle: 'Alertas en tiempo real',
    guideModeTitle: 'Modo guía experto', darkMode: 'Modo oscuro', contrastMode: 'Alto contraste', fontSize: 'Tamaño de texto',
    offline: 'Modo offline', geolocating: 'Localizando…', reviewsAdd: 'Añadir valoración', reviewsName: 'Tu nombre', reviewsText: 'Comentario',
    reviewsSend: 'Publicar', noResults: 'Sin resultados', autoctona: 'Autóctona', introducida: 'Introducida',
    tramosVisible: 'tramos visibles', nearestStretch: 'Tramo más cercano', thanksReview: '¡Gracias por tu valoración!',
    catchLogged: 'Captura registrada en tu cuaderno',
    toolsTitle: 'Herramientas', tabVedas: 'Vedas', tabPredictor: 'Buen día', tabLogbook: 'Cuaderno', tabAccess: 'Accesib.',
    accessibilityTitle: 'Accesibilidad',
  },
  en: {
    appName: 'Pesca Rioja', tagline: 'The definitive fly & spin fishing tool for La Rioja',
    searchPlaceholder: 'Search river, town or stretch…',
    filters: 'Filters', species: 'Species', tramoType: 'Stretch type', difficulty: 'Difficulty', nearMe: 'Near me',
    legend: 'Legend', layers: 'Layers', satellite: 'Satellite', topo: 'Topographic', standard: 'Standard',
    tramoSheetLength: 'Length', tramoSheetModalidad: 'Allowed methods', tramoSheetCupo: 'Daily limit', tramoSheetTalla: 'Minimum size',
    tramoSheetVeda: 'Season', tramoSheetPrecio: 'Permit', tramoSheetSpecies: 'Species present', tramoSheetConditions: 'Current conditions',
    tramoSheetAccess: 'Access', tramoSheetGallery: 'Community gallery', tramoSheetReviews: 'Reviews', tramoSheetDirections: 'Directions',
    close: 'Close', flow: 'Flow', waterTemp: 'Water temp.', clarity: 'Clarity', difficultyLabel: 'Difficulty', wadeable: 'Wadeable',
    speciesBack: 'Back to stretch', identification: 'Identification', habitatBehavior: 'Habitat & behaviour', freza: 'Spawning season',
    conservation: 'Conservation', fishingGuide: 'Practical fishing guide', techniques: 'Recommended techniques', lures: 'Recommended lures',
    hooks: 'Recommended hooks', naturalBaits: 'Natural baits', bestSeason: 'Best season', bestTime: 'Best time of day',
    idealConditions: 'Ideal conditions', legalLimits: 'Legal limits', handling: 'Catch & release handling',
    vedasTitle: 'Season calendar', logbookTitle: 'Catch logbook', predictorTitle: 'Good fishing day predictor',
    addCatch: 'Log catch', exportPdf: 'Export PDF', alertsTitle: 'Real-time alerts',
    guideModeTitle: 'Expert guide mode', darkMode: 'Dark mode', contrastMode: 'High contrast', fontSize: 'Text size',
    offline: 'Offline mode', geolocating: 'Locating…', reviewsAdd: 'Add review', reviewsName: 'Your name', reviewsText: 'Comment',
    reviewsSend: 'Post', noResults: 'No results', autoctona: 'Native', introducida: 'Introduced',
    tramosVisible: 'stretches visible', nearestStretch: 'Nearest stretch', thanksReview: 'Thanks for your review!',
    catchLogged: 'Catch logged to your logbook',
    toolsTitle: 'Tools', tabVedas: 'Seasons', tabPredictor: 'Good day', tabLogbook: 'Logbook', tabAccess: 'Access.',
    accessibilityTitle: 'Accessibility',
  },
  eu: {
    appName: 'Pesca Rioja', tagline: 'Errioxako arrantza deportiboko tresna definitiboa',
    searchPlaceholder: 'Bilatu ibaia, herria edo tartea…',
    filters: 'Iragazkiak', species: 'Espeziea', tramoType: 'Tarte mota', difficulty: 'Zailtasuna', nearMe: 'Nire ondoan',
    legend: 'Legenda', layers: 'Geruzak', satellite: 'Satelitea', topo: 'Topografikoa', standard: 'Estandarra',
    tramoSheetLength: 'Luzera', tramoSheetModalidad: 'Baimendutako modalitatea', tramoSheetCupo: 'Eguneko kupoa', tramoSheetTalla: 'Gutxieneko neurria',
    tramoSheetVeda: 'Debekaldia', tramoSheetPrecio: 'Baimena', tramoSheetSpecies: 'Bertako espezieak', tramoSheetConditions: 'Uneko baldintzak',
    tramoSheetAccess: 'Sarbidea', tramoSheetGallery: 'Komunitatearen galeria', tramoSheetReviews: 'Balorazioak', tramoSheetDirections: 'Nola iritsi',
    close: 'Itxi', flow: 'Emaria', waterTemp: 'Uraren tenp.', clarity: 'Gardentasuna', difficultyLabel: 'Zailtasuna', wadeable: 'Ibiakorra',
    speciesBack: 'Tartera itzuli', identification: 'Identifikazioa', habitatBehavior: 'Habitata eta portaera', freza: 'Arrautza-garaia',
    conservation: 'Kontserbazioa', fishingGuide: 'Arrantza gida praktikoa', techniques: 'Gomendatutako teknikak', lures: 'Gomendatutako amuak',
    hooks: 'Gomendatutako amuzkiak', naturalBaits: 'Bertako amuak', bestSeason: 'Sasoirik onena', bestTime: 'Ordurik onena',
    idealConditions: 'Baldintza idealak', legalLimits: 'Muga legalak', handling: 'Harrapatu-eta-askatu kudeaketa',
    vedasTitle: 'Debekaldi egutegia', logbookTitle: 'Harrapaketen koadernoa', predictorTitle: 'Arrantza-egun onaren iragarpena',
    addCatch: 'Harrapaketa erregistratu', exportPdf: 'PDF esportatu', alertsTitle: 'Une honetako alertak',
    guideModeTitle: 'Aditu gida modua', darkMode: 'Modu iluna', contrastMode: 'Kontraste altua', fontSize: 'Testu tamaina',
    offline: 'Offline modua', geolocating: 'Kokatzen…', reviewsAdd: 'Balorazioa gehitu', reviewsName: 'Zure izena', reviewsText: 'Iruzkina',
    reviewsSend: 'Argitaratu', noResults: 'Emaitzarik ez', autoctona: 'Bertakoa', introducida: 'Sartua',
    tramosVisible: 'tarte ikusgai', nearestStretch: 'Tarte hurbilena', thanksReview: 'Eskerrik asko zure balorazioagatik!',
    catchLogged: 'Harrapaketa koadernoan erregistratuta',
    toolsTitle: 'Tresnak', tabVedas: 'Debekaldiak', tabPredictor: 'Egun ona', tabLogbook: 'Koadernoa', tabAccess: 'Irisgarrit.',
    accessibilityTitle: 'Irisgarritasuna',
  },
  fr: {
    appName: 'Pesca Rioja', tagline: "L'outil ultime de pêche sportive à La Rioja",
    searchPlaceholder: 'Rechercher rivière, commune ou tronçon…',
    filters: 'Filtres', species: 'Espèce', tramoType: 'Type de tronçon', difficulty: 'Difficulté', nearMe: 'Près de moi',
    legend: 'Légende', layers: 'Couches', satellite: 'Satellite', topo: 'Topographique', standard: 'Standard',
    tramoSheetLength: 'Longueur', tramoSheetModalidad: 'Méthodes autorisées', tramoSheetCupo: 'Quota journalier', tramoSheetTalla: 'Taille minimale',
    tramoSheetVeda: 'Période', tramoSheetPrecio: 'Permis', tramoSheetSpecies: 'Espèces présentes', tramoSheetConditions: 'Conditions actuelles',
    tramoSheetAccess: 'Accès', tramoSheetGallery: 'Galerie de la communauté', tramoSheetReviews: 'Avis', tramoSheetDirections: 'Itinéraire',
    close: 'Fermer', flow: 'Débit', waterTemp: "Temp. de l'eau", clarity: 'Transparence', difficultyLabel: 'Difficulté', wadeable: 'Guéable',
    speciesBack: 'Retour au tronçon', identification: 'Identification', habitatBehavior: 'Habitat et comportement', freza: 'Période de frai',
    conservation: 'Conservation', fishingGuide: 'Guide pratique de pêche', techniques: 'Techniques recommandées', lures: 'Leurres recommandés',
    hooks: 'Hameçons recommandés', naturalBaits: 'Appâts naturels', bestSeason: 'Meilleure saison', bestTime: 'Meilleur moment',
    idealConditions: 'Conditions idéales', legalLimits: 'Limites légales', handling: 'Gestion attrape-relâche',
    vedasTitle: 'Calendrier des fermetures', logbookTitle: 'Carnet de captures', predictorTitle: 'Prédicteur de bon jour de pêche',
    addCatch: 'Enregistrer une capture', exportPdf: 'Exporter en PDF', alertsTitle: 'Alertes en temps réel',
    guideModeTitle: 'Mode guide expert', darkMode: 'Mode sombre', contrastMode: 'Contraste élevé', fontSize: 'Taille du texte',
    offline: 'Mode hors ligne', geolocating: 'Localisation…', reviewsAdd: 'Ajouter un avis', reviewsName: 'Votre nom', reviewsText: 'Commentaire',
    reviewsSend: 'Publier', noResults: 'Aucun résultat', autoctona: 'Indigène', introducida: 'Introduite',
    tramosVisible: 'tronçons visibles', nearestStretch: 'Tronçon le plus proche', thanksReview: 'Merci pour votre avis !',
    catchLogged: 'Capture enregistrée dans votre carnet',
    toolsTitle: 'Outils', tabVedas: 'Fermetures', tabPredictor: 'Bon jour', tabLogbook: 'Carnet', tabAccess: 'Accessib.',
    accessibilityTitle: 'Accessibilité',
  },
};
